# Generated by Django 5.0.6 on 2024-05-12 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CarModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(max_length=50)),
                ('type', models.CharField(max_length=50)),
                ('year', models.IntegerField()),
                ('price', models.IntegerField()),
            ],
            options={
                'db_table': 'cars',
            },
        ),
    ]
