# Generated by Django 5.0.6 on 2024-05-10 13:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autoparks', '0001_initial'),
        ('cars', '0002_carmodel_auto_parks'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carmodel',
            name='auto_parks',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cars', to='autoparks.autoparkmodel'),
        ),
    ]
