# Generated by Django 5.0.6 on 2024-05-10 20:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0003_alter_carmodel_auto_parks'),
    ]

    operations = [
        migrations.RenameField(
            model_name='carmodel',
            old_name='auto_parks',
            new_name='autopark',
        ),
    ]
